# Runtime directories hidden by the /var/volatile tmpfs on every boot.
d /var/volatile/tmp            1777 root root -
d /var/volatile/log            0755 root root -
f /var/volatile/log/lastlog    0664 root root -
d /var/volatile/lib            0755 root root -
d /var/volatile/lib/nfs        0755 root root -
d /var/volatile/lib/nfs/statd  0755 root root -

