#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define EG_UART_BAUDRATE 115200u
#define EG_SENSOR_PERIOD_MS 1000u
#define EG_HEARTBEAT_PERIOD_MS 5000u
#define EG_DHT_PERIOD_MS 2000u
#define EG_DEFAULT_TEMP_THRESHOLD_CENTI 3000
#define EG_ALARM_HYSTERESIS_CENTI 100

#define EG_ENABLE_DHT11 1
#define EG_USE_SYNTHETIC_ON_DHT_FAILURE 1

#endif
